"""Add qualification to sessions

Revision ID: 208a924c7d62
Revises: 005
Create Date: 2026-06-03 11:25:34.960188

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '208a924c7d62'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funnel_events', 'event_id',
               existing_type=sa.UUID(),
               comment='Client-generated UUID for idempotency; must be stable across retries',
               existing_nullable=False)
    op.alter_column('funnel_events', 'lead_id',
               existing_type=sa.UUID(),
               comment='Populated after lead creation',
               existing_nullable=True)
    op.execute("DROP INDEX IF EXISTS ix_analytics_funnel_events_type_time")
    op.alter_column('leads', 'session_id',
               existing_type=sa.UUID(),
               comment='One lead per session',
               existing_nullable=False)
    op.alter_column('leads', 'nome',
               existing_type=sa.VARCHAR(length=255),
               comment='PII: full name of the contact',
               existing_nullable=False)
    op.alter_column('leads', 'azienda',
               existing_type=sa.VARCHAR(length=255),
               comment='PII: company / organisation name',
               existing_nullable=False)
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment='PII: contact email address',
               existing_nullable=False)
    op.alter_column('leads', 'telefono',
               existing_type=sa.VARCHAR(length=50),
               comment='PII: phone number',
               existing_nullable=True)
    op.alter_column('leads', 'ruolo',
               existing_type=sa.VARCHAR(length=100),
               comment='PII: job title / role description (free text from form)',
               existing_nullable=True)
    op.alter_column('leads', 'paese',
               existing_type=sa.VARCHAR(length=100),
               comment='Country of the contact',
               existing_nullable=True)
    op.alter_column('leads', 'note',
               existing_type=sa.TEXT(),
               comment='PII: additional notes from the lead',
               existing_nullable=True)
    op.alter_column('leads', 'locale',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('leads', 'extra_qualification',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Non-canonical qualification overflow',
               existing_nullable=True)
    op.alter_column('leads', 'raw_qualification',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Verbatim qualification payload as submitted. Immutable.',
               existing_nullable=True)
    op.execute("DROP INDEX IF EXISTS ix_analytics_leads_locale_created")
    op.execute("DROP INDEX IF EXISTS ix_analytics_leads_qualification")
    op.add_column('sessions', sa.Column('qualification', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Verbatim qualification snapshot copied from the lead request'))
    op.alter_column('sessions', 'locale',
               existing_type=sa.VARCHAR(length=10),
               comment='BCP-47 locale tag (en / it / ar)',
               existing_nullable=False,
               existing_server_default=sa.text("'it'::character varying"))
    op.alter_column('sessions', 'source_flow',
               existing_type=sa.VARCHAR(length=50),
               comment='Which frontend flow triggered the capture (e.g. flowB_aml)',
               existing_nullable=True)
    op.alter_column('sessions', 'engagement_depth',
               existing_type=sa.INTEGER(),
               comment='Number of distinct screens visited',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sessions', 'visited_screens',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Ordered list of screen IDs visited during the session',
               existing_nullable=True)
    op.alter_column('sessions', 'intent_signals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Map of intent_type → visit_count accumulated during exploration',
               existing_nullable=True)
    op.alter_column('sessions', 'session_duration_seconds',
               existing_type=sa.INTEGER(),
               comment='Wall-clock duration from first screen to capture submission',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'session_duration_seconds',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Wall-clock duration from first screen to capture submission',
               existing_nullable=True)
    op.alter_column('sessions', 'intent_signals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Map of intent_type → visit_count accumulated during exploration',
               existing_nullable=True)
    op.alter_column('sessions', 'visited_screens',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Ordered list of screen IDs visited during the session',
               existing_nullable=True)
    op.alter_column('sessions', 'engagement_depth',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of distinct screens visited',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sessions', 'source_flow',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Which frontend flow triggered the capture (e.g. flowB_aml)',
               existing_nullable=True)
    op.alter_column('sessions', 'locale',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='BCP-47 locale tag (en / it / ar)',
               existing_nullable=False,
               existing_server_default=sa.text("'it'::character varying"))
    op.drop_column('sessions', 'qualification')
    op.create_index(op.f('ix_analytics_leads_qualification'), 'leads', ['target', 'obiettivo', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_leads_locale_created'), 'leads', ['locale', 'created_at'], unique=False)
    op.alter_column('leads', 'raw_qualification',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Verbatim qualification payload as submitted. Immutable.',
               existing_nullable=True)
    op.alter_column('leads', 'extra_qualification',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Non-canonical qualification overflow',
               existing_nullable=True)
    op.alter_column('leads', 'locale',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'it'::character varying"),
               existing_nullable=True)
    op.alter_column('leads', 'note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='PII: additional notes from the lead',
               existing_nullable=True)
    op.alter_column('leads', 'paese',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Country of the contact',
               existing_nullable=True)
    op.alter_column('leads', 'ruolo',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='PII: job title / role description (free text from form)',
               existing_nullable=True)
    op.alter_column('leads', 'telefono',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='PII: phone number',
               existing_nullable=True)
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(length=320),
               comment=None,
               existing_comment='PII: contact email address',
               existing_nullable=False)
    op.alter_column('leads', 'azienda',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='PII: company / organisation name',
               existing_nullable=False)
    op.alter_column('leads', 'nome',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='PII: full name of the contact',
               existing_nullable=False)
    op.alter_column('leads', 'session_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='One lead per session',
               existing_nullable=False)
    op.create_index(op.f('ix_analytics_funnel_events_type_time'), 'funnel_events', ['event_type', 'occurred_at'], unique=False)
    op.alter_column('funnel_events', 'lead_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Populated after lead creation',
               existing_nullable=True)
    op.alter_column('funnel_events', 'event_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Client-generated UUID for idempotency; must be stable across retries',
               existing_nullable=False)
    # ### end Alembic commands ###
